---
layout: cv
title: Jonathan Oliphants's CV
---
# Jonathan Oliphant
Data Scientist


## Contact
<div id="webaddress" style="display: inline-flex; gap: 1em; align-items: center; flex-wrap: wrap;">
    <a href="mailto:Jonathanoliphant13@gmail.com">Jonathanoliphant13@gmail.com</a>
    <span>385 452 1364</span>
    <a href="https://www.linkedin.com/in/jonathanoliphantb300b42ab">LinkedIn</a>
</div>

## Education

`Anticipated: July 2027`  
__Brigham Young University - Idaho__  
Bachelor of Science; Data Science  
GPA: 4.0

### Relevant Courses

- **SQL**
    - Designed and implemented relational databases, establishing efficient data structures.
    - Extracted and analyzed complex datasets to answer diverse business questions utilizing advanced queries, subqueries, and Common Table Expressions (CTEs).
    - Collaborated with a team to architect and build a functional database schema for a fictional business, gaining practical experience in database design.
- **Applied Calculus for Data Analysis**
    - Applied differentiation techniques to identify critical data points and inform predictive modeling strategies.
    - Utilized integration to compute probability of various continuous random variables.
    - Leveraged R and Mathematica to solve complex mathematical problems, enhancing computational problem-solving skills for data analysis.
- **Data Intuitions and Insight**
    - Developed compelling data visualizations using Tableau to identify trends and communicate insights effectively.
    - Prepared and delivered data-driven presentations, translating raw data into clear, actionable insights for non-technical audiences.
- **Programming with Functions**
    - Developed Python programs to efficiently read, process, and organize external datasets, laying groundwork for data pipeline understanding.
- **Introduction to Cybersecurity**
    - Gained foundational understanding of cybersecurity principles, including terminal navigation and exploring file systems within virtual machine environments, relevant for data security contexts.

## Experience

`September 2023 - Present`  
__Brigham Young University - Idaho__, Rexburg, ID  
Accessibility Specialist Team Lead

- Conducted thorough audits of university courses to ensure accessibility compliance, leading to the development of accessible video and document versions for diverse users.
- Met with other team leads to increase productivity and morale of employees in the office.
- Trained new hires on accessibility principles and overall workflow.
- Worked with AI to build scripts using JavaScript and increased efficiency of the team.

## Technical Skills

- **Programming Languages:** Python, SQL, R
- **Data Analysis & Visualization Tools:** Tableau, MySQL, Mathematica
- **Concepts & Tools:** Data Exploration, Database Management, Virtual Machines, Terminal Navigation, AI-Assisted Programming

### Research interests

Cooling, power series, optics, alchemy, planetary motions, apples.


## Education

`1654-1660`
__The King's School, Grantham.__

`June 1661 - now`
__Trinity College, Cambridge__

- Sizar

`1667 - death`
__Trinity College, Cambridge__

- Fellow



## Awards

`2012`
President, *Royal Society*, London, UK

Associate, *French Academy of Science*, Paris, France



## Publications

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Journals

`1669`
Newton Sir I, De analysi per æquationes numero terminorum infinitas. 

`1669`
Lectiones opticæ.

etc. etc. etc.

### Patents

`2012`
Infinitesimal calculus for solutions to physics problems, [SMBC](http://www.techdirt.com/articles/20121011/09312820678/if-patents-had-been-around-time-newton.shtml) patent 001


## Occupation

`1600`
__Royal Mint__, London

- Warden
- Minted coins

`1600`
__Lucasian professor of Mathematics__, Cambridge University



<!-- ### Footer

Last updated: May 2013 -->